# Initialized `__init__.py` generated by ipm.
# This is the entry file for this Infini package.
# Documents at https://ipm.hydroroll.team/

from .events import register as events_register
from .handlers import register as handlers_register
from .interceptors import register as interceptors_register

from pathlib import Path
from infini.internal import require
from ipm.models.ipk import InfiniProject


project = InfiniProject(Path(__file__).resolve().parent.parent)
for requirement in project.requirements:
    require(requirement)

__all__ = ["events_register", "handlers_register", "interceptors_register"]
